pipeline {
    agent any

    environment {
        BUILD_DIR = "dist/html"         // เปลี่ยนตาม angular.json
        DEPLOY_PATH = "/var/www/html"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Angular App') {
            steps {
                sh 'ng build --configuration production'
            }
        }

        stage('Deploy to Local Directory') {
            steps {
                sh '''
                sudo rm -rf $DEPLOY_PATH/*
                sudo cp -r $BUILD_DIR/* $DEPLOY_PATH/
                '''
            }
        }
    }
}
