apiVersion: v1
kind: Service
metadata:
  name: sutthiporn-service
spec:
  type: NodePort
  selector:
    app: sutthiporn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 #<VPS-IP>:30080
